# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://douking.github.io
date_format: "ordinal"
title: 一江春水的博客
favicon: /favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 一江春水


# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: douking

# ---------------- #
#      Socials     #
# ---------------- #
mail: wyk8916@gmail.com
github_username: DouKing
# douban_username: DouKing
# facebook_username: DouKing
# weibo_username: DouKing
# zhihu_username: DouKing
# twitter_username: DouKing

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
# duoshuo_username: DouKing
# disqus_username: Douking
# 在使用 disqus 的时候可点击显示多说评论框
# lazy_load_duoshuo: true
# gitment评论
gitment_owner: DouKing
gitment_repo: airplane
gitment_client_id: ec293b9bf0ed2c6e3c07
gitment_secret: dde919bd7c6b705d537cc82ab092b7a80c81edd6

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#     analytics_id: 

# ---------------- #
#      Datas       #
# ---------------- #
# skill_software_keywords: [Objective-C, Swift]
# skill_mobile_app_keywords: [iOS]
# skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
