# Basic
title: 醉江月
subtitle: 自强不息，厚德载物
welcome_message: 欢迎来到我的博客
description: 来自中国的iOS开发者，努力学习中。。。
# creator: <a href="http://onev.cat">@onevcat</a>

url: "http://douking.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 项目, description: 我的项目, url: 'https://github.com/DouKing'}
    - {title: 寺库, description: 寺库, url: 'http://www.secoo.com/'}
    # - {title: 订阅, description: 邮件订阅本站, url: '//store.objccn.io/subscribe'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: douking
    # duoshuo:
# Social
social:
    weibo: Pretty_kai-_-
    github: douking
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: wyk1016@126.com

# Google Analytics
ga:
#     id: UA-25719337-1
#     host: onevcat.com
